name: Automacao

on:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      folder:
        description: "Select the folder to run tests from"
        required: true
        default: "Cadastro"
        type: choice
        options:
          - Cadastro
          - Falha

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Run Cypress Tests
        run: npm run cypress:run -- --spec "cypress/integration/test/${{ github.event.inputs.folder }}/**/*.spec.js"
        env:
          CI: true
